### ISSUE TITLE
pyparsing.ParseException: Expected {& | | term | < | > | = term}, found '*'

### ISSUE THREAD

**Issue by AnneBeyer** [cpllab/syntaxgym-core#1]
Hi, I tried using * to get the total surprisal for all regions as described [here](https://cpllab.github.io/syntaxgym-core/suite_json.html#formal-definition), but got the above pyparsing exception.

I think the asterisk is simply missing from the region definition in line 22 in syntaxgym-core/syntaxgym/prediction.py
Could you check that, please?

Thank you!

**Comment by hans** [comment]
Good catch, thanks! This has been fixed and pushed in a new version (0.5.4).
